### ISSUE TITLE
Module Warning on compile

### ISSUE THREAD

**Issue by elilemons** [webplan-pro/currency-list#3]
Hello! I super appreciate this package.

That being said, whenever I compile I get this warning:

```
WARNING in ./node_modules/currency-list/lib/index.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../src/index.ts': Error: Can't resolve '../src/index.ts' in '/Users/elilemons/Documents/Dev/web-client/node_modules/currency-list/lib'
```

1.0.7 doesn't seem to have this issue so I reverted back to it for now.

Thank you!

**Comment by tuturis** [comment]
> 

Hi @elilemons ! thanks:)

About the error - I can't reproduce it locally with 1.0.8, I'd appreciate it if you could show steps on how to reproduce the error.

**Comment by elilemons** [comment]
It's just running `npm start` with my application.

We are using the LTS npm (16.4.2) and Webpack 4.41.2. It's an "older" application. Do you think this could be why?

**Comment by tuturis** [comment]
> It's just running `npm start` with my application.
> 
> We are using the LTS npm (16.4.2) and Webpack 4.41.2. It's an "older" application. Do you think this could be why?

Yes it's possible, but until I can't reproduce the issue I can not confirm it :)
